### PR TITLE
Create modal to get iOS users to add to home screen

### PR DESCRIPTION
**Pull request by ImNotRog**

### CODE REVIEW

**Comment by ky28059** [comment]
Shall put the link Sean sent here as well https://web.dev/customize-install/; seems like a cool thing to support

**Comment by ky28059** [comment]
IMG-1613
Shall also put here that of these two designs, the left one is preferable as the right one (which is what we currently have) obscures the top part of WATT; users who are going to WATT who urgently need to see the schedule won't be able to see it at a glance with the right version.

**Comment by SheepTester** [comment]
Note that on iPads, the share button is on the top right of the screen (last time I checked...which was a few years ago)

**Comment by ky28059** [comment]
Also, before we do this, we should probably make service workers more ideal on ios
https://github.com/facebook/create-react-app/issues/7237

**Comment by SheepTester** [comment]
I believe you can call `update()` on a ServiceWorkerRegistration (which you can get by doing `await navigator.serviceWorker.getRegistration()`, among others) to force the browser to check for updates

Having a control centre to allow users to force update is always a good just-in-case tool

**Comment by ky28059** [comment]
This is a stale PR! Hopefully can unstaleify and finish over winter break, along with merging schoology. Note that concerns about service worker shenanigans on mobile have been resolved with aggressive updating via the page view API.

**Comment by ky28059** [comment]
Will work on this after tailwind is merged. This should be a lot easier with headless-ui modals which allow full customization, as opposed to heavy overriding of reactstrap's modal.

**Comment by ky28059** [comment]
Moving this to a new branch

**Pull request closed without merging**
