### PR TITLE
Schoology Integration

### PR DESCRIPTION
**Pull request by ImNotRog**
This is the PR for Schoology Integration, which is still very much in progress.

### CODE REVIEW

**Comment by ky28059** [comment]
Haven't got around to looking at the code for this yet but will examine later™. The preview looks great (and even better, functions amazingly)! Small CSS changes can probably be made though (circle / spinner squishing, border thickness, etc.).

**Comment by ImNotRog** [comment]
Some interesting ideas to implement after we get the basics working:

- [ ] Let users manually input assignments; this would require changing up user data and messing around with a lot of code, but it's pretty much necessary
- [ ] Have cool effects with clicking and calendars, i.e. clicking the box for a day in the dashboard brings you to upcoming with a search query for that day

**Comment by ytchang05** [comment]
Screen Shot 2021-11-29 at 7 12 24 PM

As much as I would love for the next school day to not exist in the future, sadly its not the case.

**Comment by ImNotRog** [comment]
> Screen Shot 2021-11-29 at 7 12 24 PM
> 
> As much as I would love for the next school day to not exist in the future, sadly its not the case.

Very aware of this problem, will probably resolve this soon:tm:

**Comment by ky28059** [comment]
I think we can do some more cleanup and then merge some time soon (hopefully this weekend or next week).

**Comment by ImNotRog** [comment]
TODO before a reasonable merge:

- [ ] user-created custom assignments
- [ ] modal/popup for individual assignments

Once those two are completed, the basics of sgy integration are essentially done.

**Comment by ky28059** [comment]
The "next school day" issue still exists. Checking classes during an ongoing school day will insist the next school day started some hours ago. Perhaps either only display the *next* school day or have some text that school is in progress, started x hours ago.
image
Credit to the tall and intelligent @royjeong06.

**Comment by ImNotRog** [comment]
Sgy Data loses state after changing from classes tab

**Comment by ky28059** [comment]
Hrmm, merging is bad. I'll recreate this PR.

**Pull request merged**
